mesosphere/marathon-lb

- Dockerfile
- run
- service/haproxy/run
Alpine is much smaller but it suffers from severe DNS issues. It lacks
support for search domains and tries to resolve a dns name via all
configure nameservers and returns the first answer. Since we keep a
non-mesos dns server for backup, sometimes this one is faster and we get
NXDOMAIN for internal names.
- https://github.com/gliderlabs/docker-alpine/issues/8
- https://github.com/gliderlabs/docker-alpine/issues/11
> Use debian as base image and bash for scripts

- marathon-update-haproxy.py
We should enable `redispatch` by default. See the HAProxy docs for details on what this does: https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4-option%20redispatch
cc @discordianfish
> Enable HAProxy redispatch by default.

- marathon-update-haproxy.py
I ran a benchmark and marathon-lb crashed:
```
servicerouter: reading running config from /marathon-lb/haproxy.cfg
servicerouter: updating tasks finished, took 0.0192270278931 seconds
servicerouter: received event of type status_update_event
servicerouter: fetching apps
Traceback (most recent call last):
File "/marathon-lb/marathon-update-haproxy.py", line 1210, in <module>
process_sse_events(marathon, args.haproxy_config, args.group)
File "/marathon-lb/marathon-update-haproxy.py", line 1153, in process_sse_events
processor.handle_event(data)
File "/marathon-lb/marathon-update-haproxy.py", line 1047, in handle_event
self.reset_from_tasks()
File "/marathon-lb/marathon-update-haproxy.py", line 1034, in reset_from_tasks
self.__apps = get_apps(self.__marathon)
File …
```
> Handle request errors gracefully, rather than aborting entirely.

- Dockerfile
- README.md
- marathon-update-haproxy.py
With this, LB exposure becomes 'opt-in', rather than on-always (as with
the current implementation). To opt in to LB exposure, add a label to
the app definition to specify the LB.
For example, if you start one LB with `--group external`, and another with
`--group internal`, all apps which have the following label would be
exposed on both:
```json
{
"labels":{
"HAPROXY_GROUP":"external,internal"
}
}
```
cc @discordianfish
> Update documentation, make groups mandatory.

- README.md
- marathon_lb.py
- tests/test_marathon_lb.py
Using port 81 by default is difficult because it's a privileged port.
Also added it back on by default, now that we're not binding to a
privileged port.
cc @felixb @scalp42
> Switch default appid port to 9091.

- marathon_lb.py
Fix the error that were abnormally terminated when running without the path of the healthchecks of the marathon v0.13.0
> Fix the error that were abnormally terminated

- run
I noticed that I cannot pass an asterisk to `--group`(using docker run or marathon-lb/run) and get the marathon-lb.py script to find all marathon apps.
This is a possible fix. Other options are `set -f` in marathon-lb/run or another `--all-groups` option in marathon-lb.py.
> Fix to stop interpolation of escaped asterisk

- tests/test_marathon_lb.py
In preparation for some other work, this adds a test for config generation for http vhost generation. In a newly cloned copy of the repo, the patch applies cleanly and the test succeeds.
> Add vhost creation test

- marathon_lb.py
- tests/test_marathon_lb.py
This is dependent on #48 
Git message:
This patch adds no new functionality, but refactors some code out of the config() function:
* Create a new function, generateHttpVhostAcl() which returns a string to add to config()'s http{,s}_frontends strings
* The code in config() is replaced by appending the return strings of generateHttpVhostAcl() to http{,s}_frontends.
This particular change likely doesn't make much sense on its own, but it required for the next pull request I'm about to submit.
For testing, I manually verified that the config generated was identical, and the tests all succeed, particularly the test introduced in #48, which tests this exact functionality.
> Refactor vhost ACL generation

- marathon_lb.py
- requirements.txt
Make marathon-lb Python 2 compatible using the six compatibility package.
> Use six 2x3 compatibility

- run
With set -u, referencing $HAPROXY_SYSCTL_PARAMS will cause errors like "/marathon-lb/run: line 70: HAPROXY_SYSCTL_PARAMS: unbound variable". This effectively break existing setups.
> Fix unbound variable

- README.md
- marathon_lb.py
- tests/test_marathon_lb.py
This is dependent on #49 
Git commit message:
Allow a Marathon user to request multiple vhosts for a single service port by putting semi-colon-delimited hostnames in the application's HAPROXY_{0}_VHOST Marathon label, requiring the following changes:
- In the case where a vhost label contains a delimiter, use a combination of two newly-added templates HAPROXY_HTTP_FRONTEND_ACL_ONLY and HAPROXY_HTTP_FRONTEND_ROUTING_ONLY instead of the current HAPROXY_HTTP_FRONTEND_ACL
- In the traditional case of a single hostname in the application label, HAPROXY_HTTP_FRONTEND_ACL is still used
- Add a test case for multiple vhosts
All the previous tests succeed, and the newly added test tests the particular functionality introduced in the PR.
> Add support for multiple vhosts for a single service port

- marathon_lb.py
marathon-lb has always supported multiple --marathon/-m arguments. However the current code only uses those when polling. When using SSE the first host is hard coded.
This is okayish for DCOS where we usually only use one RRDNS host `-m http://master.mesos:8080` but bad for Mesos/Marathon deployments without mesos-dns. This PR fixes that by cycling through the hosts, making get_event_stream() return the next in the list whenever it's called.
> In SSE mode, on failure cycle through hosts instead of hard coded first one

- marathon_lb.py
`do_reset` doesn't have an `event`, leading to crashing event processing threads.
> remove access to undeclared event.data variable in do_reset

- README.md
- marathon_lb.py
- tests/test_marathon_lb.py
This PR sets secure SSL ciphers by default, turns off SSLv3 and forces TLS v1.2 which has been default in all popular browsers since Feb 2014.
It also adds the ability to set cert options in addition to defining a certificate.
I also renamed sslCertOptions in the HAPROXY_FRONTEND_HEAD template to sslCert since the corresponding label was always called `HAPROXY_0_SSL_CERT`.
I added HAPROXY_0_BIND_OPTIONS for specifying additional bind options.
This allows users to explicitly specify insecure ciphers if they so desire for e.g. backwards compatibility.
> Set default secure ssl ciphers

- tests/test_code_style.py
I want to know in which file, line and for what reason the pep8 check failed. With this change I'll get output like
```
-------------------- >> begin captured stdout << ---------------------
/home/lukas/repo/mesosphere/marathon-lb/marathon_lb.py:649:13: E131 continuation line unaligned for hanging indent
--------------------- >> end captured stdout << ----------------------
```
instead of the assertion error only.
> remove error output suppression for pep8 checks

- run
Single quotation mark is added when running Docker container using event mode. 
[Docker run command]
```
docker run -e "PORTS=8080" --privileged --net=host mesosphere/marathon-lb:v1.1.1 event http://172.26.111.14:8080 -m http://192.168.99.100:8080 -l http://172.26.111.14:8080 --group external
```
[Marathon log]
```
spray.http.IllegalUriException: Illegal URI reference, unexpected character ':' at position 5:
'http://172.26.111.14:8080'
^
marathon_1 |
at spray.http.Uri$.fail(Uri.scala:775)
at spray.http.parser.UriParser.complete(UriParser.scala:429)
at spray.http.parser.UriParser.parseReference(UriParser.scala:60)
at spray.http.Uri$.apply(Uri.scala:231)
at spray.http.Uri$.apply(Uri.scala:203)
at spray.httpx.RequestBuilding$RequestBuilder.apply(RequestBuilding.scala:36)
at …
```
> Registering a HTTP callback has failed in event mode

- marathon_lb.py
- tests/test_marathon_lb.py
I think the TCP health check of HAProxy should be used if application's mode is "http" but health check is "tcp".
Because an application depends on it's health check.
How do you think about it?
> Use TCP health check of HAProxy if app's health check protocol is "TCP"

- marathon_lb.py
- tests/test_marathon_lb.py
> For path ACLs, use backend instead of hostname.

- README.md
- marathon_lb.py
- tests/test_marathon_lb.py
This change fixes the HTTP to HTTPS redirects, which were previously
broken. In order to use the redirect, you must at least specify a VHost.
> Fix HTTP to HTTPS redirects.

- marathon_lb.py
In case we missed one or more SSE messages, periodically refresh the app
state.
> Peridiocally (every 5m) refresh app state.

- build-haproxy.sh
My system is ubuntu 14.04, the haproxy building get a error.
```
/usr/bin/ld: /usr/local/lib//liblua.a(loadlib.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [haproxy] Error 1
```
Add a USE_DL=1 in build options and remove "-ldl" in LDFLAGS was fixed.
> fix the haproxy build error in Ubuntu 14.04

- marathon_lb.py
- tests/test_marathon_lb.py
It's referred to "http://blog.haproxy.com/2015/10/14/whats-new-in-haproxy-1-6/"
> Need 'stats socket /var/run/haproxy/socket' for seamless reloading

- README.md
- getconfig.lua
- getpids.lua
- marathon_lb.py
- tests/test_marathon_lb.py
The `/_haproxy_getconfig` returns the HAProxy config as it was at the
time of process initialization.
> Add `/_haproxy_getconfig` endpoint.

- marathon_lb.py
- tests/test_marathon_lb.py
If multiple apps share a VHost, and one uses a redirect but the other
does not, the redirect rule may get applied to the wrong VHost.
> Fix redirect for shared VHosts.

- Dockerfile
This will give us OpenSSL 1.0.2, among other things, which has better
support for hardware acceleration of TLS.
> Bump Debian version from Jessie -> Stretch.

- Longhelp.md
- lrucache.py
- marathon_lb.py
When Marathon fails over, it will come back up without any task health
information. Unfortunately, this will cause marathon-lb to treat the
backends as being down, and will remove them. With this, we keep around
an LRU cache of task health states to reduce the likeliness of removing
backends after a failover by reusing the previously known health state.
> Add basic LRU cache for health status.

- Longhelp.md
- README.md
- marathon_lb.py
- tests/test_marathon_lb.py
- tests/test_utils.py
- utils.py
The following Marathon LB fix is a workaround for a Marathon issue: https://github.com/mesosphere/marathon/issues/3636
The above issue means Marathon does not return service ports when using apps with IP-per-task.  Upshot is Marathon-LB does not work for these apps.
Ideally, I'd really like to see a fix for the above issue, but I'm offering this PR as a temporary work-around.
The change in this PR auto-assigns a service port for each host discovery port when the app is using IP-per-task.  The ports are not persistent across restart of the marathon-lb process, and the ports are not exposed so this fix is only useful when using vhost (where you don't actually care what value of service port is chosen).  The feature is activated by specifying a min/max port as additional arguments - these …
> Auto-assign service ports for IP-per-container tasks when Marathon does not

- Longhelp.md
- config.py
- marathon_lb.py
- tests/test_marathon_lb.py
Some ACLs may be affected by order. For example, if you're using VHost
and path ACLs that are shared amongst backends, the ordering of the ACLs
will matter. With HAPROXY_{n}_BACKEND_WEIGHT you can change the ordering
by specifying a weight. Backends are sorted from largest to smallest
weight.
To address #152.
> Allow weighting of backends.

- run
By default, if `systcl` fails it results in a hard failure. In other
words, the main `run` script will exit and the container will fail.
By setting `HAPROXY_SYSCTL_NONSTRICT` to a non-empty string, the
`sysctl` failures will be treated as soft failures.
This was introduced to workaround in issue where Docker will mount /proc
within the container as read-only, even when the container is running in
privileged mode.
cc @lingmann @alberts
> Optionally make sysctl setting a soft failure.

- README.md
- run
marathon_lb.py already has support for multiple certs. However the Docker container run script currently only processes a single cert. This PR adds support for multiple certs exported as
HAPROXY_SSL_CERT0 .. HAPROXY_SSL_CERT100.
I also renamed the default cert /etc/ssl/cert.pem instead of /etc/ssl/mesosphere.com.pem
and changed the short arg `-c` to the equivalent long arg `--command` since we're using long args for everything else.
> Allow to specify multiple certs in Docker ENV

- run
By setting `SSL_CERTS` above the if statement (for generating the
default self-signed cert), the cert will never be generated.
cc @lloesche @lingmann @kartick
> Fix minor regression from #169.

- bluegreen_deploy.py
It was previously very hard to understand what was happening in the `bluegreen_deploy.py` script with the looping constructs in `process_json` and `get_app_info`, instead refactor these methods to be more straight forward and readable.
> Refactor `process_json` and `get_app_info` in bluegreen_deploy.py

- bluegreen_deploy.py
- tests/test_bluegreen_deploy.py
Small bug fix 😦 
~~We need to compare 150% of instances when scaling against the
old_app (previously existing_app) instances. otherwise we always
scale to deployment target on first go.~~
Update: Better explanation added below...
rename scale_up_app_instances to scale_new_app_instances to avoid
confusion.
> correct bug when scaling app instances

- bluegreen_deploy.py
- tests/test_bluegreen_deploy.py
@brndnmtthws This tests that when `args.max_wait` is exceeded, the function `swap_bluegreen_apps` will log the timeout and return false instead of throwing an exception. (thus allowing the script to exit naturally) This is done by using the new method `max_wait_not_exceeded` as the condition for the `while` loop in `swap_bluegreen_apps`. This means that a timeout will only happen after a full iteration of the `while` loop, ensuring we are not left with any undeleted tasks which we know about.
As well since we no longer raise an exception on timeout I've simply set the scripts exit code based on the return value of `do_bluegreen_deploy`. This allows the script to exit gracefully on timeout but with a non-zero exit code to indicate failure.
This should prevent an infinite loop due to …
> correct and add test for `swap_bluegreen_apps` timeout

- bluegreen_deploy.py
- tests/test_bluegreen_deploy.py
@brndnmtthws this should address both #190 and #191 Normally I would just work on the original PR with you, but I saw a chance to kill two birds with one PR.
There is one difference here, and that's that i simply wait for apps to be fully drained (no qcur and no scur) before i delete their tasks.
> Bugfix - Scale new_app separately from killing old_app

- .travis.yml
- Longhelp.md
- README.md
- config.py
- marathon_lb.py
- requirements.txt
This PR add the ability to define a set of trusted IPs or networks to an http or tcp backend per port or globally.
Example: 
```json
$  cat marathon.json 
{
"id": "nginx",
"mem": 128.0,
"cpus": 0.5,
"instances": 1,
"labels": {
"HAPROXY_0_MODE": "http",
"HAPROXY_0_BACKEND_NETWORK_ALLOWED_ACL": "127.0.0.1 192.168.0.1/25",
"HAPROXY_GROUP": "*"
},
"container": {
"docker": {
"portMappings": [
{
"servicePort": 0,
"protocol": "tcp",
"containerPort": 443,
"hostPort": 0
},
{
"servicePort": 0,
"protocol": "tcp",
"containerPort": 80,
"hostPort": 0
}
],
"image": "nginx",
"network": "BRIDGE",
"priviledged": false
},
"type": "DOCKER",
"volumes": []
},
"healthChecks": [
{
"portIndex": 0,
"protocol": "TCP",
"timeoutSeconds": 20,
"intervalSeconds": 60,
"gracePeriodSeconds": 300,
"maxConsecutiveFailures": …
```
> Add network_allow ACLs to HTTP and TCP backends

- zdd.py
- The continue statement in [find_tasks_to_kill](https://github.com/mesosphere/marathon-lb/blob/e55903e436c4ead8f6d02497e69e904d5bf88ba7/zdd.py#L271) doesn't allow [listeners](https://github.com/mesosphere/marathon-lb/blob/e55903e436c4ead8f6d02497e69e904d5bf88ba7/zdd.py#L274) to be populated, as long as [haproxy pids](https://github.com/mesosphere/marathon-lb/blob/e55903e436c4ead8f6d02497e69e904d5bf88ba7/zdd.py#L124) length is > 1.
- This causes the script to go into infinite loop whenever [max wait exceeds](https://github.com/mesosphere/marathon-lb/blob/e55903e436c4ead8f6d02497e69e904d5bf88ba7/zdd.py#L263) and length of haproxy_pids continue to remain greater than 1. It doesn't force kill the old_apps after max wait as empty listeners is passed to …
> populated listeners in zdd to prevent infinite loop

- zdd.py
Currently when `args.initial_instances` is greater than `deployment_target_instances`(`HAPROXY_DEPLOYMENT_TARGET_INSTANCES`), zdd script goes into infinite loop.
It sets `app['instances'] = args.initial_instances` [here](https://github.com/mesosphere/marathon-lb/blob/f9cb0426e4401c1e725596b37f0fe9c02d627e04/zdd.py#L516) as a part of [prepare_deploy](https://github.com/mesosphere/marathon-lb/blob/f9cb0426e4401c1e725596b37f0fe9c02d627e04/zdd.py#L560) function call. And then the control flows to [swap_zdd_apps](https://github.com/mesosphere/marathon-lb/blob/f9cb0426e4401c1e725596b37f0fe9c02d627e04/zdd.py#L578),  and only way to return from this recursive function is when [ready_to_delete_old_app](https://github.com/mesosphere/marathon-lb/blob/f9cb0426e4401c1e725596b37f0fe9c02d627e04/zdd.py#L3 …
> Over-ride initial instances when it is greater than deployment target instances to prevent infinite loop in zdd.

- marathon_lb.py
By default, we do not set a connect/read timeout on sockets when in SSE
mode. It's possible that the TCP socket may actually be stale
(somehow?), so we'll set a timeout on the socket. By default, we depend
on the platform setting.
This will hopefully address issues #230, #234, and #238.
> Set a socket connect/read timeout for SSE mode.

- Longhelp.md
- README.md
- marathon_lb.py
- tests/test_zdd.py
- zdd.py
Currently zdd supports either completely blue or completely green deployments, but there are usecases when both blue and green have to be live at the same time.
Ex: Lets say current deployment color is blue with 10 instances, there is a new deployment(green color) which first needs to be deployed on 2 instances (so traffic is split 80:20) and then if nothing breaks, green can be scaled up to full capacity.
This PR supports such kind of deployments with the help of new  flag `HAPROXY_DEPLOYMENT_NEW_INSTANCES` or `--new-instances` command-line-arg to zdd.py
How it works?
- When  `--new-instances` flag is specified, it creates only the specified number of instances in new app(and deletes the same number of instance from old app). So if old app has 10 instances and zdd is run with …
> Blue green hybrid deployment with zdd

- marathon_lb.py
If you put the example like `-m http://mesos-1:8080 -m http://mesos-2:8080` can give a wrong idea that is necessary use more the one `-m` use multiples marathon instancies. But it really need to pass multiples parameters to the `-m` like `-m http://mesos-1:8080 http://mesos-2:8080`
> More clear -m help document

- Longhelp.md
- config.py
- marathon_lb.py
- tests/test_marathon_lb.py
Renamed `HAPROXY_{n}_HTTP_BACKEND_PROXYPASS` and
`HAPROXY_{n}_HTTP_BACKEND_REVPROXY` labels to
`HAPROXY_{n}_HTTP_BACKEND_PROXYPASS_PATH` and
`HAPROXY_{n}_HTTP_BACKEND_REVPROXY_PATH` respectively. Also added
equivalent `_GLUE` templates for modifying the actual template.
> Fix proxypass & revproxy (see #264).

- service/haproxy/run
When doing a graceful reload, use `pidof haproxy` rather than catting
the pidfile to make sure that we send SIGUSR1 to _all_ existing HAProxy
instances.
This is to address #267.
> Use `pidof` instead of pidfile w/ reload.

- utils.py
> Fallback to `ports` on older Marathon versions.

- marathon_lb.py
This is the correct path of the haproxy service on systems without the
UsrMerge, like Ubuntu / older Debians. This was causing us to take the
init.d path instead of the systemd path on our Ubuntu-based cloud infra.
> marathon_lb: Also check /lib/systemd/system/haproxy.service

- marathon_lb.py
run_server function [here](https://github.com/mesosphere/marathon-lb/blob/481520be6470fae2c6b46015a4b98782acab9800/marathon_lb.py#L1475) is expecting a new argument `marathon_ca_cert` (which is not optional) , but it was not being passed by the caller [here](https://github.com/mesosphere/marathon-lb/blob/481520be6470fae2c6b46015a4b98782acab9800/marathon_lb.py#L1607), so whenever you run marathon_lb.py it was resulting in the below error:
`TypeError: run_server() missing 1 required positional argument: 'marathon_ca_cert'` . 
There are no test cases for run_server, so this bug has effected tags `1.3.3`, `1.3.4` and `1.3.5` as well.
> added marathon_ca_cert as argument while calling run_server

- Longhelp.md
- config.py
- marathon_lb.py
- tests/test_marathon_lb.py
See issue #198 for details.
Use case:
```
Ex: An app exposes two ports, one for the application, one for its healthchecks:
portMappings": [
{
"containerPort": 9000,
"hostPort": 0,
"servicePort": 0,
"protocol": "tcp"
},
{
"containerPort": 9001,
"hostPort": 0,
"servicePort": 0,
"protocol": "tcp"
}
]
HAPROXY_0_BACKEND_HEALTHCHECK_PORT_INDEX=1 will make it so that the port 9001
is used to perform the backend healthchecks.
```
This is a usual pattern to expose administrative contexts on it's own port when using http://www.dropwizard.io/ . 
cc @brouberol as the original author of the original patch used at OVH. 
(we're currently testing this in our staging environment here at Zedge)
> Allow a healthcheck to take place on a specified port index 

- marathon_lb.py
- service/haproxy/run
Don't use `pidof haproxy` as input to the `-sf` argument.
`pidof haproxy` can return multiple pids instead of the latest haproxy pid, which can break the reload chain. 
This will hopefully fix the problem where MLB hangs indefinitely and stops refreshing the haproxy config.
Added log message while waiting for new haproxy pid as we have seen the loop to run forever before. Without this print out the user knows nothing about the state of MLB.
Similar problems:
* https://groups.google.com/forum/#!topic/marathon-framework/R6RkBHaFtBo
* https://github.com/QubitProducts/bamboo/issues/79
> Correctly create haproxy chain

- tests/test_utils.py
- utils.py
This should resolve #313.
[Test app 1](https://gist.github.com/brndnmtthws/677a715f2d2c7dec40c45dbd1a1296a6)
[Test app 2](https://gist.github.com/brndnmtthws/a9323c61e97564e2eb789eb88ae7b118)
[Results](https://gist.github.com/brndnmtthws/0cb5137ae0ec1922bc95100a7cb36566)
This can be tested by pulling the `fix-ip-per-task` Docker image tag.
> Fix for IP per task in Marathon 1.3+.

- run
We need to carefully escape arguments which are passed into the generated run script. We should also avoid expanding the args when doing a comparison.
> Properly escape args in script (to fix #337).

- marathon_lb.py
- tests/test_marathon_lb.py
fix for #342 
Contains a unit test to verify the scenario.
This fix sets the backend_weight of the app to -1 when its template uses a domain2backend map. By doing this it gets appended to the end of the section, instead of getting thrown in somewhere in the middle (which caused the unreachable service problems).
> domain2backend use_backend ordering #342

- build-haproxy.sh
From haproxy Makefile: `This is for standard Linux >= 2.6.28 with netfilter, epoll, tproxy and splice`
> Activate all linux >= 2.6.28 haproxy features

- README.md
- config.py
- tests/test_marathon_lb_haproxy_options.py
This allows for setting global default haproxy options via the `HAPROXY_GLOBAL_DEFAULT_OPTIONS` environment variable as a comma-separated list.
> add HAPROXY_GLOBAL_DEFAULT_OPTIONS via environment variable

- build-haproxy.sh
Probably best read commit-by-commit.
Before (`mesosphere/marathon-lb:v1.4.2`):
```
root@2bc441c311bf:/marathon-lb# haproxy -vv
HA-Proxy version 1.6.9 2016/08/30
Copyright 2000-2016 Willy Tarreau <willy@haproxy.org>
Build options :
TARGET  = linux2628
CPU     = x86_64
CC      = gcc
CFLAGS  = -g -fno-strict-aliasing -Wdeclaration-after-statement
OPTIONS = USE_LINUX_SPLICE=1 USE_LINUX_TPROXY=1 USE_LIBCRYPT=1 USE_ZLIB=1 USE_DL=1 USE_OPENSSL=1 USE_LUA=1 USE_PCRE=1 USE_PCRE_JIT=1
Default settings :
maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with OpenSSL version : OpenSSL …
```
> HAproxy build improvements

- zdd.py
> Use app instances if label is unavailable in ZDD.

- haproxy_wrapper.py
- service/haproxy/run
- set pipe to inheritable (this changed in Python 3.4, and I missed it
in my previous testing)
- run HAProxy in daemon mode (durr)
> haproxy_wrapper fixes.

- Dockerfile
- README.md
- common.py
- marathon_lb.py
- requirements.txt
- run
- utils.py
Earlier issues #35 and #114 made things better in this department. However,
when running marathon-lb with a large (400+ applications) marathon instance,
there are still problems.
These problems can be traced back to Python itself, unfortunately:
http://stackoverflow.com/questions/21797753/efficiently-reading-lines-from-compressed-chunked-http-stream-as-they-arrive
Python requests uses urllib under the covers, and there are implicit issues
when 7.5 MB of JSON comes back on a single line, as we're seeing when certain
events are emitted. These events are deployment_info and deployment_success at
a minimum, there may be more.
By switching to PycURL, as noted in the Stack Overflow post, we bypass this
whole issue. We use an HTTP library that handles this particular edge case
well, reducing CPU …
> Use PycURL for fetching event streams

- Longhelp.md
- README.md
- config.py
- marathon_lb.py
- tests/test_marathon_lb.py
This also adds a new `HAPROXY_{n}_ENABLED` option, which lets you
enabled/disable individual backends for an app.
This resolves issues #402 and #403.
> Introduce new `--strict-mode` option.

- utils.py
World's smallest PR :1st_place_medal:
This changes `CurlHttpEventStream` to have the same SSL verification behavior as `Marathon`.
Context: I'm running DC/OS Enterprise Edition (1.8.7) and MLB v1.5.0. I wanted to configure MLB to use HTTPS, but since DC/OS uses it's own internal CA, the certs aren't valid.
Standard API requests through the `Marathon` object work fine because it disables SSL verification by default.
```python
self.__verify = False
if ca_cert:
self.__verify = ca_cert
```
Using server side events fails because `CurlHttpEventStream` does not disable SSL verification by default.
```
2017-02-27 15:39:27,165 marathon_lb: starting event processor thread
2017-02-27 15:39:27,166 marathon_lb: SSE Active, trying fetch events from https://marathon.mesos:8443/v2/events
2017-02-27 …
```
> Fix pycurl SSL Verification

- config.py
A new template needs a corresponding add_template(), "setter", and if it
is "overridable", to append a label.
I also left a comment without modification when a template is missing
the "setter".
> config: Fix missing labels referenced in overridable templates

- README.md
- run
As you might know if your Marathon requires authentication it is possible to pass in the auth-credentials parameter to marathon_lb.py in order to get authorized.
This PR includes the changes to get the user & password from a running VAULT instance defining environment variables. If this PR gets approved we will able to add these variables to the config.json of the marathon-lb package in the DC/OS universe.
> Get --auth-credentials from a VAULT instance

- marathon_lb.py
- tests/test_utils.py
- utils.py
- zdd.py
This change addresses a bug introduced marathon-lb version 1.9.0 which affects apps using `USER` networking mode with containers as well as on DC/OS versions 1.9 and lower. Specifically apps with empty `portMappings`.
The encountered error looks similar to this:
```
File "/marathon-lb/utils.py", line 376, in get_port_mapping_ports
for p in port_mappings
TypeError: 'NoneType' object is not iterable
```
> Fix return type of get_app_port_mappings

- README.md
Proposed change to README.md to warn users about use of zdd.py on a production environment.
> Change README.md to add note about use of zdd.py on prod environments.

- Dockerfile
- Longhelp.md
- README.md
- haproxy_wrapper.py
- marathon_lb.py
- run
- service/haproxy/run
- syslogd/run
- syslogd/syslog.conf
Corresponding config changes can be found here: https://github.com/mesosphere/universe/pull/1462
* Address various race conditions resulting in never-ending `Waiting for pid...`: Added these args:
```
--retry-reload        Retry reload if unsuccessful after --reload-interval
seconds. (default: False)
--reload-interval RELOAD_INTERVAL
When --retry-reload enabled, wait this long before
attempting another reload. (default: 10)
```
* Address `[ALERT] 278/182040 (164) : sendmsg logger #1 failed: No such file or directory (errno=2)` and `[ALERT] 278/182040 (164) : sendmsg logger #2 failed: No such file or directory (errno=2)`: Enable syslogd logging to container stdout (default to off) by setting the `HAPROXY_SYSLOGD` environment variable or `container-syslogd` value in `options.json` like so: …
> Add container syslogd support and fix 'Waiting for Pids' race condition

- Dockerfile
- marathon_lb.py
Addresses the problem of continuously throwing the following error:
```
2017-11-03 05:31:36,031 marathon_lb: Caught exception
Traceback (most recent call last):
File "/marathon-lb/marathon_lb.py", line 1799, in <module>
process_sse_events(marathon, processor)
File "/marathon-lb/marathon_lb.py", line 1700, in process_sse_events
for event in events:
File "/marathon-lb/marathon_lb.py", line 239, in get_event_stream
for line in resp.iter_lines():
File "/marathon-lb/utils.py", line 241, in _split_lines_from_chunks
for chunk in chunks:
File "/marathon-lb/utils.py", line 226, in _iter_chunks
self._check_curl_errors()
File "/marathon-lb/utils.py", line 230, in _check_curl_errors
raise pycurl.error(*f[1:])
pycurl.error: (28, 'Operation too slow. Less than 1 bytes/sec transferred the last 300 …
```
> Fix reconnect logging and timing depending on error type

- marathon_lb.py
We introduced lightweight events with MARATHON_EE-1673. These do not
include the complete groups and make the events much smaller. This
should not only ease the consumption but also the workload for
Marathon. Furthermore Marathon LB should only request the events
it actually needs.
This patch should close MARATHON-8036 and MARATHON-8047.
> Filter events on server side, in order to decrease load on Marathon

- marathon_lb.py
Patch to archive the previous configs to `/tmp`. It will keep a history of haproxy.cfg, domain_map and app_map in /tmp/{hap_cfg.1, dom_map.1 app_map.1} etc based on the number of versions configured. It will help in debugging any issues with config after the config is re-generated.
> config archiving

- marathon_lb.py
This issue doesn't surface when the equivalent http rules are used because the map is given a different weight: https://github.com/mesosphere/marathon-lb/blob/v1.6.0/marathon_lb.py#L723
The same weighting is not given to the https map in this particular block, which sometimes injects the map in the middle of the path acls. Everywhere else the weight is added, so this must have just been missed?
> Fix ordering of acls that include paths when using haproxy map with https

- Dockerfile
Cherry pick of 8534066a1293d33e6d52c39f2d6324c40a03394c
Makes two changes:
* Split the tini retrieve, verify, and install into a separate Dockerfile RUN command.
* Use multiple keyservers.
> Use multiple keyservers for gpg verify of tini during Docker build

- build.bash
- marathon_lb.py
Config validation was not working as expected. After regenerating config while removing invalid apps, the generated haproxy.cfg remained the same as pre-validation.
This primarily happened because it was writing a haproxy.cfg meant only for validation test to the actual live haproxy.cfg path on disk. Later when the logic to check for changes that should trigger a reload, it detected no change because the validation test file was in the same spot.
Another problem was that if the last app in the list happened to be the bad one, the bad config would actually make it into the final config.
This PR also reduces the necessary N calls to list apps where N=total number of apps in marathon which can cause significant stress on large deployments.
> Fix bug in config validation and reduce marathon calls

- Dockerfile
Somewhere upstream, a dependency was introduced such that:
`python3` depends on `dh-python`
`dh-python` depends on `dpkg-dev`
`dpkg-dev` depends on `make`
So uninstalling make (via `apt-get purge -y --auto-remove`) removes python3, and everything breaks.
This turns `make` from a build dependency to a runtime dependency - probably not ideal, but it's the easiest workaround for now.  We'll want to look at discussing how to change/prevent this in the future.
> Work around python3 > dh-python > dkpg-dev > make dependency

- run
This PR includes a check for the reload command before appending it to the reload file. Without this, the `reload_haproxy.sh` file is slowly filled with multiple `sv reload ...` commands.
CC: @justinrlee @drewkerrigan @jdef
> Append reload command only if it doesn't exist already

- ci/backends/docker_bridge.json
- ci/backends/docker_host.json
- ci/backends/docker_ippc.json
- ci/backends/ucr_bridge.json
- ci/backends/ucr_host.json
- ci/backends/ucr_ippc.json
- ci/backends_1.9/docker_bridge.json
- ci/backends_1.9/docker_host.json
- ci/backends_1.9/docker_ippc.json
- ci/backends_1.9/ucr_host.json
- ci/ci-integration.sh
- ci/test_marathon_lb.py
Adding both CI and integration tests for Marathon LB. These tests are triggered whenever a PR is created. 
The CI builds and launches Marathon LB based on a docker image. The integration tests launch simple UCR & Docker backends which are then used to test against Marathon LB.
> Adding MLB Integration Tests to CI

- marathon_lb.py
Addresses this error found when attempting to validate invalid labels:
```
2018-04-13 07:47:03,204 marathon_lb: Unexpected error! 
Traceback (most recent call last): 
File "/marathon-lb/marathon_lb.py", line 1729, in make_config_valid_and_regenerate 
group_https_by_vhost) 
TypeError: generateAndValidateTempConfig() takes 5 positional arguments but 6 were given
```
Also introduces a some cleanup of temp files generated by config validation.
> Address bug in config validation for invalid labels

- config.py
- marathon_lb.py
- requirements-dev.txt
- tests/test_marathon_lb.py
This PR introduces consistent IDs of backend servers. Thanks to this reloading HA-Proxy no longer results in backend server uptime data being reset - the backend server state is properly preserved across restarts in general and there is no downtime due to health checks needing to re-deploy.
There are two possible solutions to this approach:
* stateful
* hashing
The stateful approach requires a global state for each backend servers group which will be persisted across reloads. On top of that removal of backend servers need to be tracked and the corresponding server IDs need to be removed from the global state. 
The hashing approach is much simpler - there is a shared state but only during a reload, and the removals of backend servers are handled implicitly (i.e. given ID is simply not …
> Make server ids persistent across reloads

- Dockerfile
This PR should fix #593 Debian buster doesn't support libcurl3 anymore hence the issue of libcurl not found when executing the docker image from dockerhub.
> Replaced libcurl3 to libcurl4

- marathon_lb.py
if service doesn't have label HAPROXY_DEPLOYMENT_TARGET_INSTANCES it will throw an error because an undefined value of new['labels']['HAPROXY_DEPLOYMENT_TARGET_INSTANCES']
logs:
```
2018-01-04 09:41:08,631 marathon_lb: received event of type instance_changed_event
2018-01-04 09:41:12,781 marathon_lb: received event of type status_update_event
2018-01-04 09:41:12,782 marathon_lb: received event of type instance_changed_event
2018-01-04 09:41:12,782 marathon_lb: fetching apps
2018-01-04 09:41:12,818 marathon_lb: GET http://marathon.mesos:8080/v2/apps?embed=apps.tasks
2018-01-04 09:41:12,826 marathon_lb: got apps ['/shipping-rules', '/crm', '/logger', '/notifications-http', '/autoscaler', '/discount-rules', '/notifications-consumer', '/wishlist', '/memsql', '/marathon-lb', '/products', …
```
> fix: undefined HAPROXY_DEPLOYMENT_TARGET_INSTANCES

- .dockerignore
- .gitignore
- Dockerfile.devkit
- Makefile
- README.md
- ci/test_marathon_lb_dcos_e2e.py
- config.py
- requirements-dev.txt
- tests/test_marathon_lb.py
Uses a `Makefile` to drive testing. Allows locally running unit/integration tests with just docker/curl installed. Includes the two commits from #606. Will close that in favor of this one.
> Update testing infrastructure 

- marathon_lb.py
This PR should fix #578 — I've included an additional check before removing temp map files.
CC: @cailian824, @drewkerrigan, @justinrlee
> #578 Remove temp map files only after checking for map config

- marathon_lb.py
- tests/test_marathon_lb.py
Currently, using the `HAPROXY_REDIRECT_TO_HTTPS` label together with a (single) virtual host doesn't work because the `use_backend` config isn't added. It seems that `haproxy_http_frontend_acl_only` is being used instead of `haproxy_http_frontend_acl` in one of the paths.
> Bind the backend to the frontend when redirectHttpToHttps is used

- Longhelp.md
- config.py
- tests/test_marathon_lb.py
Due to a wrong end double quote location in the HAPROXY_HTTP_BACKEND_REVPROXY_GLUE template, it option was generating the haproxy configuration erroneously and making the HAPROXY_{n}_HTTP_BACKEND_REVPROXY_PATH option have unexpected behavior.
I double checked with the [HAProxy Documentation](https://www.haproxy.com/doc/aloha/7.0/haproxy/http_rewriting.html#rewrite-anywhere-in-the-response-using-regexes)
`rspirep <search> <replace> [<cond>]`
> Typo on HAPROXY_HTTP_BACKEND_REVPROXY_GLUE template.

- README.md
Links `Using marathon-lb` to a page on the github wiki instead of
`docs.mesosphere.com` so the links can be updated without a PR when the
URLs change.
Fixes: #559
> readme: point to github wiki

- tests/Dockerfile
Changes the base image to `mesosphere/marathon-lb:latest`. Since this
image requires a copy of `/marathon-lb`, reusing the existing image
instead of creating another one helps with caching. Also since the
latest `cassandra-driver` no longer works on `debian:jessie` and
`mesosphere/marathon-lb:latest` is already built upon `debian:buster`
using it as the base makes sense.
> tests/dockerfile: update base image

- utils.py
Curl will not send the auth credentials to a host that it has been
redirected to by default. Set `pycurl.UNRESTRICTED_AUTH` which is the
option for `--location-trusted` to allow sending the name + password to
all hosts that the site may redirect to.
Fixes: #632
> utils: send auth to any host redirected to

- Dockerfile
updated, tests passed. 
```
marathon-lb on  master on 🐳 v18.09.3 took 9m 22s
[I] ➜ make test-integration
+ Build container image mikejennings/marathon-lb:5d6393b
+ Pushing image to hub
docker push mikejennings/marathon-lb:5d6393b
The push refers to repository [docker.io/mikejennings/marathon-lb]
f63d319a8064: Pushed
e1cd2bc04ce0: Layer already exists
5aab828cc6d0: Layer already exists
5e02ae959b09: Layer already exists
6325e828e90a: Layer already exists
9bc98e914376: Layer already exists
5d6393b: digest: sha256:19a46b06e643183786143e16ee7b51553bbcedd5788888f59e078d5baefad68b size: 1580
+ Build devkit image mesosphere/marathon-lb-devkit:latest
+ Discovering Cluster URL
+ Cluster URL: http://172.17.0.4
+ Discovering Public Node IP
+ Public Node IP: 172.17.0.6
+ Integration Testng with …
```
> updated to 1.9.5

- Dockerfile
Fixes segfaults from https://github.com/haproxy/haproxy/commit/8d85aa44dabb772cf99360c41143486875f3e383 fixed via http://git.haproxy.org/?p=haproxy-1.9.git;a=commitdiff;h=ac4be10
> docker: update to haproxy 1.9.8

- marathon_lb.py
When grouping services with HAPROXY_DEPLOYMENT_GROUP without a health check marathon-lb crashes.
https://github.com/mesosphere/marathon-lb/issues/637
> checks if healthChecks is a key of app before checking length (#637)

- marathon_lb.py
`self.host` cycles through available Marathon URLs, and it was accessed twice in `get_event_stream`, which made it access the same Marathon instance, if two URLs were supplied, which is especially profound if the instance being accessed over and over again is down.
> Use self.host property once in get_event_stream

- marathon_lb.py
Though a series of updated pr's the `plan-format=light` param was lost.
Add it back in.
Fixes: #642
> mlb: fix event stream subscription params

- requirements.txt
This should help remove potential conflicts between `urllib3` and `requests`. `requests` anyways transitively depends on `urllib3`, so removing this shouldn't be a problem.
> Fix #647 - Remove urllib3 conflicts

- Dockerfile
v2.0.7 includes a few key HTTP/2 fixes.
> Bump HAProxy to 2.0.7

- marathon_lb.py
Suppose you have an app that needs to warming up at first.
( e.g. http response code: 503 -> 200 )
When start a app that has healthChecks
task have healthChecks Results property but don't have any element in array at first
But it add backend server in haproxy
Eventually, 
Before healthChecks run once at first
request's packet will flow in a app that don't check healthChecks
#655
> Fix bug in checking healthChecks at first (#655)

- Dockerfile
HAProxy 2.0.10 has been released with a few major fixes: https://www.mail-archive.com/haproxy@formilux.org/msg35488.html
> docker: bump haproxy to 2.0.10

- marathon_lb.py
- requirements.txt
It's helpful for debugging cluster issues to have different user agents for each component.
> Specify marathon-lb user agent

- marathon_lb.py
Will generate nice log like this:
```
marathon_lb: running config is different from generated config - reloading
marathon_lb: ---
marathon_lb: +++
marathon_lb: @@ -1041,11 +1041,6 @@
marathon_lb:    mode tcp
marathon_lb:    use_backend platform_proj_37226
marathon_lb:
marathon_lb: -frontend platform_proj_37360
marathon_lb: -  bind *:37360
marathon_lb: -  mode tcp
marathon_lb: -  use_backend platform_proj_37360
marathon_lb: -
marathon_lb:  frontend platform_proj_38903
marathon_lb:    bind *:38903
marathon_lb:    mode tcp
marathon_lb: @@ -3106,11 +3101,6 @@
marathon_lb:    mode tcp
marathon_lb:    server server.com.10_1_1_1_31077 10.1.1.1:31077 id 4244
marathon_lb:
marathon_lb: -backend platform_proj_37360
marathon_lb: -  balance roundrobin
marathon_lb: -  mode tcp
marathon_lb: -  server …
```
> Use difflib to log haproxy config changes

- Dockerfile
- Longhelp.md
- README.md
- config.py
- tests/test_marathon_lb.py
- tests/test_marathon_lb_haproxy_options.py
As of 2.0.0, HAProxy includes a Prometheus exporter module that can be built into a binary during build time.
To build with the official Prometheus exporter module, `make` should be run with the following `EXTRA_OBJS` flag:
`make TARGET=linux-glibc EXTRA_OBJS="contrib/prometheus-exporter/service-prometheus.o"`
Once built, prometheus-exporter can be enabled in haproxy.cfg:
```
listen stats
bind 0.0.0.0:9090
balance
mode http
stats enable
http-request use-service prometheus-exporter if { path /metrics }
```
For more infromation, see this [official blog post](https://www.haproxy.com/blog/haproxy-exposes-a-prometheus-metrics-endpoint/)
> Add prometheus-exporter to HAProxy

- Dockerfile
https://www.mail-archive.com/haproxy@formilux.org/msg36877.html
> docker: bump haproxy to 2.0.14, fix CVE-2020-11100
