mesosphere/marathon-lb

- marathon-update-haproxy.py
The bug was introduced in 3c83b1433.
> fix callback mode

- README.md
- run
> Support reading templates from mesos sandbox

- marathon-update-haproxy.py
I think renaming was forgotten.
> Rename service router to load balancer or marathon-lb

- README.md
> Clarify docs.

- Dockerfile
- marathon-update-haproxy.py
- run
Also fixed some bugs in `run`.
> Switch from python 2 to 3.

- README.md
- marathon-update-haproxy.py
> Allow all templates to be specified via labels.

- README.md
- marathon_lb.py
- run
- tests/test_marathon_lb.py
In place of #23 
cc @aladagemre
> Fikrimuhal master

- run
> Fix `run` breakage.

- marathon_lb.py
Fixes https://github.com/mesosphere/marathon/issues/2781
> close file descriptors before calling reload cmd

- marathon_lb.py
> fixed set_mode

- marathon_lb.py
Related to https://github.com/mesosphere/marathon-lb/issues/37
Thanks for looking at it!
On side note we should switch to something else like bottle but my python-fu might be limited.
> fix wsgi by returning bytes

- marathon_lb.py
> Handle SSE connection errors gracefully.

- bluegreen_deploy.py
- common.py
- marathon_lb.py
- requirements.txt
- tests/test_bluegreen_deploy.py
This is to address #34. Depends on #51.
> Marathon http auth

- .travis.yml
- marathon_lb.py
- tests/test_bluegreen_deploy.py
this fixes #54, at least it works for me when running marathon-lb with python2
> fix python 2 support

- run
> Add more useful error message about $PORTS

- marathon_lb.py
- tests/test_marathon_lb.py
Make sure we set 'timeout tunnel' so that websockets work correctly.
> Set more sane HAProxy defaults.

- README.md
Added informations about the HAProxy statistics page
> updated readme - haproxy statistics

- README.md
- marathon_lb.py
- tests/test_marathon_lb.py
Disclaimer: I have not yet tested this, but it might work.
> Support for path-based routing (HAPROXY_{n}_PATH).

- README.md
- marathon_lb.py
- tests/test_marathon_lb.py
added support for haproxy groups  per service group along with test cases and documentation
> added support for haproxy groups  per service group along with test cases and documentation

- README.md
- common.py
- tests/test_bluegreen_deploy.py
- this option allows to pass marathon credentials
via docker params
- updated README.md
> Add --auth-credentials option

- marathon_lb.py
> Actually stop the event processor thread.

- marathon_lb.py
- tests/test_marathon_lb.py
> Fix HTTPS path routing where only 1 vhost exists.

- marathon_lb.py
To prevent a thundering herd problem, apply a backoff before
reconnecting to the stream after an exception.
> Apply backoff on SSE stream failures.

- marathon_lb.py
- requirements.txt
> Use requests directly, instead of sseclient.

- bluegreen_deploy.py
Set a 300s upper-bound time limit on the amount of time to wait for
HAProxy to drain connections.
> bluegreen_deploy.py: time limit on draining.

- marathon_lb.py
- tests/test_marathon_lb.py
You can enable HSTS with `HAPROXY_{0}_USE_HSTS` and
`HAPROXY_{0}_BACKEND_HSTS_OPTIONS`.
It occurred to me after merging #121 that HSTS should be opt-in, rather than on by default.
> Make HSTS opt-in only.

- Longhelp.md
- config.py
- marathon_lb.py
- tests/test_marathon_lb.py
Rebased and reworked against master 
See https://github.com/mesosphere/marathon-lb/pull/127 for history
> rebases and reworked against master

- Longhelp.md
- bluegreen_deploy.py
If the max wait timeout is exceeded, we should just continue with the deployment.
cc @JamesAwesome
> Fix regression in ZDD draining timeout.

- service/haproxy/run
Reviving this to address #177 and #149.
> Remove iptables rules before starting HAProxy.

- Dockerfile
- README.md
- run
This implements #197 
Should be fully backwards compatible.
> Allow to specify --group and --marathon value via ENV

- run
Fixes unbound variable error introduced in #199
> Hotfix: unbound variable error

- bluegreen_deploy.py
- tests/test_bluegreen_deploy.py
> Add a pre-kill hook to ZDD deploy.

- build-haproxy.sh
> Bump HAProxy to 1.6.5, enable gzip.

- common.py
- marathon_lb.py
- tests/test_common.py
- zdd.py
> Add log level support

- Longhelp.md
- tests/test_utils.py
- tests/zdd_apps.json
- utils.py
> Deprecate 'ports' in favour of 'portDefinitions'.

- Dockerfile
Remove the not used port 81 and add 9091
> Add HAPROXY_HTTP_FRONTEND_APPID_HEAD port

- utils.py
> Check for NoneType.

- tests/test_zdd.py
- zdd.py
- zdd_exceptions.py
Added Exception handling to Zdd so that it throws different exceptions for different failure scenarios and exits with a different exit code for each of them. 
This makes life easier when zdd module or script is invoked automatically as different actions can be defined based on Exception Type/Exit Status.
> Added Custom Exception handling with exit status for various failure scenarios

- marathon_lb.py
When reloading, make sure there's actually a new PID by doing some basic
set math.
To address #267.
> Check for new PID after reload.

- config.py
See https://github.com/dcos/dcos-docs/pull/458
> Downcase vhost.

- .travis.yml
- README.md
- point build status badge to Jenkins
- remove .travis.yml
> (VELOCITY-882) Migrate unit testing from Travis to Jenkins

- Longhelp.md
- config.py
- tests/test_marathon_lb.py
> Remove extra slash added to request when using backend proxypass (#284)

- .dockerignore
- Dockerfile
Minor tweaks plus..
* Install the runtime dependencies first so that that layer can be cached most of the time
* Be sure to install the latest Python packages even if a system package is already installed
> More Docker improvements

- service/haproxy/run
There have been reports of multiple copies of the same firewall rules.
Let's make sure we always remove all rules which may have been
installed.
> Ensure we remove all firewall rules.

- common.py
> Be more correct with auth token expiry.

- common.py
- marathon_lb.py
> Set timeouts on requests.

- Longhelp.md
- config.py
- tests/test_marathon_lb.py
- tests/test_marathon_lb_haproxy_options.py
A method rename was incomplete in the HAPROXY_DEFAULT_GLOBAL_OPTIONS pr that introduced a bug; this is the fix.
> fix bug introduced in HAPROXY_DEFAULT_GLOBAL_OPTIONS PR

- marathon_lb.py
This should (properly) resolve #366 and #393.
> Fix missing date label for ZDD.

- common.py
- zdd.py
These are very minor fixes that I came across while reading this code.
> General Fixes.

- Dockerfile
* HAProxy 1.7.2
* Build with the Debian Lua packages
> HAProxy updates

- README.md
- build.bash
- config.py
- haproxy_wrapper.py
- marathon_lb.py
- requirements-dev.txt
- tests/test_marathon_lb_haproxy_options.py
- utils.py
Fix issues reported by flake8, most importantly that the `set_ip_cache` function was not working.
> Python cleanup: make nosetests the default test runner, coverage, flake8

- README.md
In setting up my local environment to run the marathon-lb tests I ran into two issues. This PR adds a small troubleshooting section that lists the issues along with the confirmed fixes.
Fixes https://jira.mesosphere.com/browse/DCOS_OSS-1513
> README: add dev setup troubleshooting to Contributing section

- marathon_lb.py
This PR adds automatic sanitizing of configuration such that when an app containing invalid `HAPROXY_{n}_xxx` labels is introduced, it is excluded from configuration and a valid haproxy config is generated from the remaining apps.
The net result being that a single badly-configured application can no longer cause marathon-lb config updates to stop for all apps in the same cluster (or haproxy group).
> exclude bad apps from generated config

- Dockerfile
https://www.mail-archive.com/haproxy@formilux.org/msg28502.html
> bump to haproxy v1.8.3

- marathon_lb.py
merging to new branch to test build process.
* config archiving
* fixed the base case while creating first file
> config archiving (#532)

- Longhelp.md
Please check the JIRA issue for details: https://jira.mesosphere.com/browse/DOCS-2533
> Update the documentation wrt. HAPROXY  connection mode

- marathon_lb.py
- utils.py
This PR fixes #594. We can land this once https://github.com/mesosphere/marathon/pull/6211 lands.
CC: @timcharper
> #594 Follow redirects from non-leaders in Marathon 1.7

- marathon_lb.py
This should fix #613, reported by @jcmcken.
CC: @timcharper @brndnmtthws @drewkerrigan @justinrlee
> Correctly validate global daemon flag

- zdd.py
In our stack, due to some resource constraints, Marathon sometimes can't fulfill the scaling requests of `zdd.py`, especially since the final step (when number of new app instances has grown beyond number of old instances) might need a resource overcommitment by more than 150%.
To mitigate this, we introduced a `linear-increase` option to `zdd.py` which allows a continuous rollout, similar to a regular restart of the app in Marathon, but with the benefit of draining existing connections.
> Introduce "linear-increase" parameter to zdd.py.

- run
enable password authentication via env variables.
> add basic auth password authentication

- Dockerfile
- Makefile
- README.md
JIRA issue: [DCOS_OSS-5374](https://jira.mesosphere.com/browse/DCOS_OSS-5374)
> Bump HAProxy to 2.0.3

- marathon_lb.py
JIRA issue: [DCOS_OSS-5369](https://jira.mesosphere.com/browse/DCOS_OSS-5369)
> Fix the usage of condition variable

- ci/ci-integration.sh
- marathon_lb.py
JIRA issue: [DCOS_OSS-5370](https://jira.mesosphere.com/browse/DCOS_OSS-5370)
> Make the list of excluded states complete
